name: restaurant_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  cupertino_icons: ^0.1.2
  equatable:
  meta:
  flutter_bloc: ^4.0.0
  firebase_core:
  cached_network_image:
  url_launcher:
  smooth_star_rating: '1.0.2'
  flutter_staggered_grid_view:
  flutter_rating_bar: ^2.0.0+2
  bloc:
  intl:
  numberpicker:
  flutter_datetime_picker:
  bubble_tab_indicator:
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true


  assets:
  - assets/bg.jpg
  - assets/glogo.png
  - assets/logo.png
  